# Request
string target_id # uuid of part to be moved (robot, part, effector, ..)
passform_msgs/Condition condition
rcl_interfaces/Parameter[] parameters
geometry_msgs/Wrench wrench
---
# Result
passform_msgs/Location final_location
---
# Feedback
passform_msgs/Location current_location
